<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b5991a60-2da6-4923-a453-1f1ecf4d68a5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeLab\HomeLab\HomeLab.csproj" />
  </ItemGroup>

</Project>
